---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lpg
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
parameters:
  type: {{ .Values.lpg.storage.type }}
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
