{{- if .Values.blackbox.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.blackbox.serviceName }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: blackbox
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Values.Namespace }}
spec:
  ports:
  - name: blackbox
    port: 9115
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: blackbox
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: {{ .Values.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/blackbox-cm.yaml") . | sha256sum }}
      labels:
        app: blackbox
    spec:
      priorityClassName: lpg
      containers:
      - name: blackbox
        image: {{ .Values.blackbox.image }}
        args:
        - --config.file=/config/blackbox.yaml
        ports:
        - name: http-metrics
          containerPort: 9115
          protocol: TCP
        resources:
          requests:
            memory: {{ .Values.blackbox.resources.requests.memory }}
            cpu: {{ .Values.blackbox.resources.requests.cpu }}
          limits:
            memory: {{ .Values.blackbox.resources.limits.memory }}
            cpu: {{ .Values.blackbox.resources.limits.cpu }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: blackbox-config
          mountPath: /config
      volumes:
      - name: blackbox-config
        configMap:
          name: blackbox-config
{{- end }}
