---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: lpg
  labels:
    app: lpg
    app.kubernetes.io/managed-by: {{ .Release.Service }}
value: 1000000
globalDefault: false
description: "lpg priority class"
