apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  {{- range $key, $val := .Values.env.configmap }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
