{{- if .Values.ExternalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}-external-secret
  labels:
    app.kubernetes.io/name: {{ .Values.appname }}
    app.kubernetes.io/instance: {{ .Values.appname }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secrets-manager
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.name }}

{{- end}}