{{- if .Values.volumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appname }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appname }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.appname }}-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumeClaim.resources.requests.storage }}
{{- end}}