{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.secretStore.aws.service }}
      region: {{ .Values.secretStore.aws.region }}
      auth: 
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStore.aws.auth }}
            key: {{ .Values.secretStore.aws.access_key }}
          secretAccessKeySecretRef:
            name: {{ .Values.secretStore.aws.auth }}
            key: {{ .Values.secretStore.aws.secret_key }}
{{- end }}