apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}