---
{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.appname }}-storage
  labels:
    app.kubernetes.io/name: {{ .Values.appname }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Values.Namespace }}
parameters:
  type: {{ .Values.storageClass.type }}
provisioner: {{ .Values.storageClass.provisioner }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- end}}