{
 "title": "AWS Load Balancing",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETEHUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ALB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP statuses (LB)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_alb_httpcode_elb_2_xx_count_sum{tag_ingress_k8s_aws_stack!=\"\"}) by (tag_ingress_k8s_aws_stack)",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }} | 2xx"
      },
      {
       "expr": "sum(aws_alb_httpcode_elb_3_xx_count_sum{tag_ingress_k8s_aws_stack!=\"\"}) by (tag_ingress_k8s_aws_stack)",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }} | 3xx"
      },
      {
       "expr": "sum(aws_alb_httpcode_elb_4_xx_count_sum{tag_ingress_k8s_aws_stack!=\"\"}) by (tag_ingress_k8s_aws_stack)",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }} | 4xx"
      },
      {
       "expr": "sum(aws_elb_httpcode_backend_5_xx_sum{dimension_load_balancer_name!=\"\"}) by (dimension_load_balancer_name)",
       "legendFormat": "{{ dimension_load_balancer_name }} | 5xx"
      }
     ]
    },
    {
     "title": "HTTP statuses (backend)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_alb_httpcode_target_2_xx_count_sum{tag_ingress_k8s_aws_stack!=\"\"}) by (tag_ingress_k8s_aws_stack)",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }} | 2xx"
      },
      {
       "expr": "sum(aws_alb_httpcode_target_3_xx_count_sum{tag_ingress_k8s_aws_stack!=\"\"}) by (tag_ingress_k8s_aws_stack)",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }} | 3xx"
      },
      {
       "expr": "sum(aws_alb_httpcode_target_4_xx_count_sum{tag_ingress_k8s_aws_stack!=\"\"}) by (tag_ingress_k8s_aws_stack)",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }} | 4xx"
      },
      {
       "expr": "sum(aws_elb_httpcode_backend_5_xx_sum{dimension_load_balancer_name!=\"\"}) by (dimension_load_balancer_name)",
       "legendFormat": "{{ dimension_load_balancer_name }} | 5xx"
      }
     ]
    },
    {
     "title": "Response time (LB)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(aws_alb_target_response_time_average{tag_ingress_k8s_aws_stack!=\"\"}) by (tag_ingress_k8s_aws_stack)",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }}"
      }
     ]
    },
    {
     "title": "Active connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(aws_alb_active_connection_count_sum{tag_ingress_k8s_aws_stack!=\"\"}[5m])",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }}"
      }
     ]
    },
    {
     "title": "Processed bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(aws_alb_processed_bytes_sum{tag_ingress_k8s_aws_stack!=\"\"}[5m])",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }}"
      }
     ]
    },
    {
     "title": "Request count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (tag_ingress_k8s_aws_stack) (rate(aws_alb_request_count_sum{tag_ingress_k8s_aws_stack!=\"\"}[5m]))",
       "legendFormat": "{{ tag_ingress_k8s_aws_stack }}"
      }
     ]
    }
   ]
  },
  { "title": "ELB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "HTTP statuses (backend)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_httpcode_backend_2_xx_sum{dimension_load_balancer_name!=\"\", tag_kubernetes_io_service_name!=\"\"}) by (tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }} | 2xx"
    },
    {
     "expr": "sum(aws_elb_httpcode_backend_3_xx_sum{dimension_load_balancer_name!=\"\", tag_kubernetes_io_service_name!=\"\"}) by (tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }} | 3xx"
    },
    {
     "expr": "sum(aws_elb_httpcode_backend_4_xx_sum{dimension_load_balancer_name!=\"\", tag_kubernetes_io_service_name!=\"\"}) by (tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }} | 4xx"
    },
    {
     "expr": "sum(aws_elb_httpcode_backend_5_xx_sum{dimension_load_balancer_name!=\"\", tag_kubernetes_io_service_name!=\"\"}) by (dimension_load_balancer_name)",
     "legendFormat": "{{ dimension_load_balancer_name }} | 5xx"
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_latency_average{dimension_load_balancer_name!=\"\", tag_kubernetes_io_service_name!=\"\"}) by (tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Unhealthy host count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_un_healthy_host_count_sum{dimension_load_balancer_name!=\"\", tag_kubernetes_io_service_name!=\"\"}) by (tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_elb_request_count_sum{dimension_load_balancer_name!=\"\", tag_kubernetes_io_service_name!=\"\"}) by (tag_kubernetes_io_service_name)",
     "legendFormat": "{{ tag_kubernetes_io_service_name }}"
    }
   ]
  }
 ]
}