{
 "title": "Solr Dashboard",
 "description": "Solr Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "zk_host",
    "query": {
     "query": "label_values(solr_ping{zk_host=~\".+\"},zk_host)"
    }
   },
   {
    "name": "collection",
    "query": {
     "query": "label_values(solr_ping{zk_host=\"$zk_host\",collection=~\".+\"},collection)"
    }
   },
   {
    "name": "shard",
    "query": {
     "query": "label_values(solr_collections_shard_state{zk_host=\"$zk_host\",collection=\"$collection\",shard=~\".+\"},shard)"
    }
   },
   {
    "name": "replica",
    "query": {
     "query": "label_values(solr_collections_replica_state{zk_host=\"$zk_host\",collection=\"$collection\",shard=\"$shard\",replica=\".+\"},replica)"
    }
   },
   {
    "name": "base_url",
    "query": {
     "query": "label_values(solr_ping{base_url=~\".+\"},base_url)"
    }
   },
   {
    "name": "core",
    "query": {
     "query": "label_values(solr_ping{base_url=~\"$base_url\"},core)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Jetty Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_requests_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{method}}"
    }
   ]
  },
  {
   "title": "Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_response_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{status}}"
    }
   ]
  },
  {
   "title": "Dispatches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jetty_dispatches_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_buffers{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{pool}}"
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_buffers_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{pool}} {{item}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_seconds_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_heap_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Non-Heap Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_non_heap_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_pools_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{space}} {{item}}"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_threads{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Memory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_memory_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_file_descriptors{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_cpu_load{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_os_cpu_time_seconds{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_load_average{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_requests_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_time_seconds_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_client_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_server_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_timeouts_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}{{handler}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_cores{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Core Root File System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_core_root_fs_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{item}}"
    }
   ]
  },
  {
   "title": "Thread Pool Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_thread_pool_completed_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Thread Pool Submitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_node_thread_pool_submitted_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Thread Pool Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_thread_pool_running{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{executor}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_connections{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}} {{handler}} {{item}}"
    }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_requests_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_time_seconds_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_client_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_server_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_timeouts_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Field Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_field_cache_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Searcher Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_cache{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "Searcher Warm Up Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_warmup_time_seconds{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}}"
    }
   ]
  },
  {
   "title": "Searcher Cumulative Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_searcher_cumulative_cache_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_fs_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 159 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_index_size_bytes{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Searcher Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_documents{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}}/{{core}} {{item}}"
    }
   ]
  },
  {
   "title": "Update Handler Adds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_adds_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Pending Docs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_update_handler_pending_docs{base_url=~\"$base_url\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By ID",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_id_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_query_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Expunge Deletes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_expunge_deletes_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Merges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_merges_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Splits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_splits_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Optimizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_optimizes_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Rollbacks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_rollbacks_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Soft Auto Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_soft_auto_commits_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Auto Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_auto_commits_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_commits_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_errors_total{base_url=~\"$base_url\"}[1m])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  }
 ]
}