{
 "title": "Kubernetes Cluster Autoscaler (via Prometheus)",
 "description": "Super simple dashboard showing an overview of kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to prometheus.\r\n\r\nhttps://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count)\n"
    }
   ]
  },
  {
   "title": "Nodes available",
   "type": "singlestat",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\"})/sum(cluster_autoscaler_nodes_count)*100"
    }
   ]
  },
  {
   "title": "Is cluster safe to scale?",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale)"
    }
   ]
  },
  {
   "title": "Number of unscheduled pods",
   "type": "singlestat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count)",
     "legendFormat": " pods"
    }
   ]
  },
  {
   "title": "Last scaleDown activity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"scaleDown\"})"
    }
   ]
  },
  {
   "title": "Last autoscale activity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"autoscaling\"})"
    }
   ]
  },
  {
   "title": "Pod activity",
   "type": "graph",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Num Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_evicted_pods_total)",
     "legendFormat": "evicted pods"
    },
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count)",
     "legendFormat": "unscheduled pods"
    }
   ]
  },
  {
   "title": "Node activity",
   "type": "graph",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Num Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"unready\"})",
     "legendFormat": "unready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"notStarted\"})\n",
     "legendFormat": "not started"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Num nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total)",
     "legendFormat": "scaled up total"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count)",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count)\n",
     "legendFormat": "total nodes"
    }
   ]
  },
  {
   "title": "Cluster direction?",
   "type": "singlestat",
   "description": "Is the cluster scaling up, down or ticking along okay?",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total)-sum(cluster_autoscaler_scaled_down_nodes_total)"
    }
   ]
  }
 ]
}