{
 "title": "Endpoint probes (blackbox_exporter)",
 "description": "Dashboard for network endpoint probe availability",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Prober HTTP status codes",
   "type": "graph",
   "description": "Non 200 status codes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_http_status_code != 200", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Endpoint Availability",
   "type": "graph",
   "description": "Only shows endpoints under 100%. Ideally, this chart has nothing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_success[15m]) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Probe timers",
   "type": "graph",
   "description": "Displays probe timers that take over 1s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds > 1",
     "legendFormat": "{{ instance }} | {{ phase }}"
    }
   ]
  },
  {
   "title": "DNS lookup time",
   "type": "graph",
   "description": "Display endpoints that took over 1s to resolve",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds[5m]) > 0.01",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}